include:
  - local: "/gitlab-ci/general.gitlab-ci.yml"
  - local: "/gitlab-ci/build.gitlab-ci.yml"
  - local: "/gitlab-ci/docker-build.gitlab-ci.yml"
  - local: "/gitlab-ci/package.gitlab-ci.yml"
  - local: "/gitlab-ci/deploy.gitlab-ci.yml"
