services:
  organization-service:
    image: yowyob/geofence-service
    container_name: yowyob-geofence-service
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
    networks:
      - openia-main-network
    ports:
      - 8089:8081
# NETWORKS ------------------------------------------------------------------------
networks:
  openia-main-network:
    external: true