deploy:
  stage: deploy
  tags: [yowyob-cmd]
  dependencies:
    - docker-build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker pull "$IMAGE_TAG" || true
    - docker stack deploy -c docker/docker-compose-stack.yml "$SERVICE_STACK_NAME" --with-registry-auth
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      variables:
        DEPLOYMENT_ENVIRONMENT: "production"
        ENVIRONMENT: "production"
    - when: always

